### ISSUE TITLE
Executing sqlplus fails

### ISSUE THREAD

**Issue by marcfrederick** [InstantClientTap/homebrew-instantclient#31]
When trying to execute `sqlplus` after installing it using `brew install instantclient-sqlplus` I get the following error:
```
Error 6 initializing SQL*Plus
SP2-0667: Message file sp1<lang>.msb not found
SP2-0750: You may need to set ORACLE_HOME to your Oracle software directory
```
The same thing happens if I install with `--with-basiclite`

**Comment by francisceril** [comment]
+1 this!

Having the same error after upgrading to macOS Catalina. Was working great on Mojave.

**Comment by kaukas** [comment]
I don't use Catalina yet. Would anyone be able to debug and perhaps suggest a PR?

**Comment by ajaya** [comment]
Use this as an work around for now. I haven't yet debugged the core issue.

`DYLD_LIBRARY_PATH=$(brew --prefix)/lib sqlplus`

**Comment by glennimoss** [comment]
~I'm having this same issue, and setting the DYLD_LIBRARY_PATH doesn't help. (I'm also on Catalina.)
@ajaya Do you have any actual files like `sp1*.msb`? There are no such files in anything installed by homebrew, and I even went and downloaded several different versions from Oracle's site and none of them contained anything like these message files.~

Nevermind. I had some shenanigans with a local script I use to invoke sqlplus. Once I properly set the `DYLD_LIBRARY_PATH` in the script, it worked.

**Comment by jaredmeakin** [comment]
So with a fresh install I was getting the same error. 

Adding `DYLD_LIBRARY_PATH=$(brew --prefix)/lib sqlplus` to my shell's profile did indeed seem to fix it for me.

**Comment by aaronlippold** [comment]
Is there a way to put this into the install script?

**Comment by kaukas** [comment]
`DYLD_LIBRARY_PATH` is an anti-pattern, not recommended to be set it globally.

I still do not have a machine to debug and fix the problem. A PR would be welcome!

**Comment by NazariGamer** [comment]
Same issue/error on Catalina. @kaukas how can I help? Not sure what you mean with PR, let me know.

**Comment by kaukas** [comment]
If you can find a fix for the formula please let me know so that I could fix it for everyone. Unfortunately, `DYLD_LIBRARY_PATH` is a workaround, not a fix.

**Comment by NazariGamer** [comment]
@kaukas I did some investigation. 

What I found out that if you put the sqlplus files + libraries in the same folder as the instaclient-basic files there is no error. According to the official installation documentation, this is also how both packages need to be installed: https://www.oracle.com/database/technologies/instant-client/macos-intel-x86-downloads.html#ic_osx_inst

But if installing in separate directories, the library that is causing the specific error is called: libociei.dylib, which is part of the instaclient package. 

So there could be two issues with this file: 1) it cannot be found by sqlplus (because it is in another directory - path issue?) or 2) it is not authorised to execute. 

On the latter, I had to manually approve the file for execution in "system preferences --> security & privacy --> general --> allow to run" as Mac OS classified the file as "from unknown developer". After approving the library for execution, sqlplus worked normally (in the "all files in single directory scenario).

Note: I needed to do this for all libs and sqlplus due to manual copying of the fles into /usr/local/Cellar/instaclient* folders.

For completeness this is the order in which executables and libraries are called:
sqlplus
libsqlplus.dylib
libclntsh.dylib.19.1
libclntshcore.dylib.19.1
libnnz19.dylib
libsqlplusic.dylib
libociei.dylib --> Error 6 initializing SQL*Plus

As you can see sqplus is able to open a lot of the libraries from the instaclient-basic folder (running sqlplus from different folder to mimic brew current package deployment setup) except the last one, which is throwing the error reported.

I do not have knowledge on Brew formula in order to fix it, but I hope above information will help you to fix it. Let me know if you need more info, or if I need to test something. Thanks.

**Comment by NazariGamer** [comment]
Here another useful doc on getting a working installation (manual): https://zwbetz.com/install-sqlplus-on-a-mac/  and this one provides more specific details on the issue: https://stackoverflow.com/questions/37711482/how-to-install-oracle-instant-client-on-a-mac

**Comment by NazariGamer** [comment]
Ok, I think we can exclude the security issue mentioned above. I have followed instructions to allow any program downloaded from the internet to run: https://www.imore.com/how-open-apps-anywhere-macos-catalina-and-mojave and I ended up with the same error message.

So that leaves the "instaclient & sqlplus must be in the same folder" as the underlying issue.

Update 6/4/2020: I ran the command as indicated on the following page to verify files are not marked after installation through Homebrew. Another inidcation it is not a security issue: http://oraontap.blogspot.com/2020/01/mac-os-x-catalina-and-oracle-instant.html

**Comment by NazariGamer** [comment]
Hi @kaukas 
I read all the (official) docs available and contacted Oracle support. The instaclient basic files and instaclient sqplus files MUST:

- be of the same version
- be installed in the same directory

Hence, you cannot install in separate directories. 

So to formula needs to be changed to reflect the installation requirements. As I don't have knowledge on writing formulas, I hope you will be able to do it. 

Let me know if you want me to test. Thanks

**Comment by kaukas** [comment]
Hi, @exelanz. Thank you for going as far as to contact Oracle!

Did they explicitly state that you need to put sqlplus with other dylibs in the same folder for Catalina? Because they are in separate folders in Mojave and it works fine:
```sh
$ find /usr/local/Cellar/instantclient-sqlplus/19.3.0.0.0dbru
/usr/local/Cellar/instantclient-sqlplus/19.3.0.0.0dbru
/usr/local/Cellar/instantclient-sqlplus/19.3.0.0.0dbru/INSTALL_RECEIPT.json
/usr/local/Cellar/instantclient-sqlplus/19.3.0.0.0dbru/bin
/usr/local/Cellar/instantclient-sqlplus/19.3.0.0.0dbru/bin/sqlplus
/usr/local/Cellar/instantclient-sqlplus/19.3.0.0.0dbru/.brew
/usr/local/Cellar/instantclient-sqlplus/19.3.0.0.0dbru/.brew/instantclient-sqlplus.rb
/usr/local/Cellar/instantclient-sqlplus/19.3.0.0.0dbru/lib
/usr/local/Cellar/instantclient-sqlplus/19.3.0.0.0dbru/lib/libsqlplus.dylib
/usr/local/Cellar/instantclient-sqlplus/19.3.0.0.0dbru/lib/libsqlplusic.dylib
$ sqlplus -V

SQL*Plus: Release 19.0.0.0.0 - Production
Version 19.3.0.0.0
```

**Comment by NazariGamer** [comment]
Hi @kaukas, yes they did state that. I quote "Basic package and any additional Topups such as "SQL*Plus Package" or/and 'Tools Package' should be of same version and should be unzipped under same location ". This seems to be in line with the official installation documentation: 

https://www.oracle.com/database/technologies/instant-client/macos-intel-x86-downloads.html#ic_osx_inst . 

However, the official SQLPlus configuration guide mentions the environment variable DYLD_LIBRARY_PATH to influence SQLPlus behaviour:

https://docs.oracle.com/en/database/oracle/oracle-database/19/sqpug/configuring-SQL-Plus.html#GUID-5A2953BF-9E2F-450B-AFBA-EE2846C59B5E . 

But I think it is best to stick to official support & documented guidance. Hope this helps. Let me know if I need to test something.

**Comment by kaukas** [comment]
I got access to Catalina, reproduced the problem and tried to find ways to fix besides putting everything in the same folder. Will try some more, otherwise just put in the same folder.

**Comment by NazariGamer** [comment]
@kaukas also source in Oracle Dev team confirmed: use the same directory. Official support for Catalina is in the pipeline. Cheers.

**Comment by kaukas** [comment]
There's something funky about the way sqlplus loads libsqlplusic.dylib and I could not fix it. I wrapped sqlplus into a shell script that sets the `DYLD_LIBRARY_PATH`. Please try [the sqlplus-for-catalina branch](https://github.com/InstantClientTap/homebrew-instantclient/tree/sqlplus-for-catalina) and let me know if it works well for you.

**Comment by NazariGamer** [comment]
@kaukas I installed via 

`brew install https://raw.githubusercontent.com/InstantClientTap/homebrew-instantclient/sqlplus-for-catalina/Formula/instantclient-sqlplus.rb`

and it works like a charm.

As you said, there might be some quirks as Catalina is not yet officially supported by Oracle.

Thanks!

**Comment by kaukas** [comment]
Merged to master, closing.
